## 넘파이 Numpy

### 넘파이 가져오기

In [ ]:
import numpy as np

### 넘파이 배열 생성하기

In [ ]:
x=np.array([1.0,2.0,3.0])
print(x)
type(x) #numpy에서 제공하는 특수한 형태의 배열 numpy.ndarray

[1. 2. 3.]


numpy.ndarray

### 넘파이의 산술연산

In [ ]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
# x,y의 원소의 개수가 같음
print(x/2.0) #브로드캐스트 기능

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


### 넘파이의 N차원 배열

In [ ]:
A=np.array([[1,2],[3,4]])
print(A)
print(A.shape)    #(2,2) 2*2 행렬임을 알 수 있다.
A.dtype

[[1 2]
 [3 4]]
(2, 2)


dtype('int64')

In [ ]:
B=np.array([[3,0],[0,6]])
print(A+B)
print(A*B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


### 브로드캐스트
- 크기가 다른 배열을 계산해줌

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([10,20])  #B배열을 (2,2)행렬로 확대한 후 연산을 진행
print(A*B) 

[[10 40]
 [30 80]]


### 원소 접근

In [ ]:
X=np.array([[51,55],[14,19],[0,4]])
print(X)
print(X[0])
print(X[0][1])

for row in X:
  print(row)

X=X.flatten() #X를 1차원 배열로 변환(평탄화)
print(X)
X[np.array([0,2,4])] #0,2,4번째 인덱스 얻기

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]


array([51, 14,  0])